### PR TITLE
Change .gpla format to binary, improving performance massively

### PR DESCRIPTION
**Pull request by DJLevel3**
As described above, the .gpla file is now a binary format that performs far better on save and load. Technically it's base64 encoded so it still works with the file save and load functions built into osci-render, but the decoded data is pure binary.

### CODE REVIEW

**Comment by jameshball** [comment]
### Platforms and software tested

List any platforms tested. E.g. Windows or macOS

Also list any DAWs you are using to test. E.g. Ableton, Reaper, Logic.

### Testing performed

Describe in detail any testing you've performed that is specific to the feature or bugfix this PR addresses.

### Testing checklist

- [ ] Tested PR on the standalone app
- [ ] Tested PR when using as an audio plugin, e.g. VST or AU
- [ ] Added unit tests to `osci-render-test.jucer` project when relevant
- [ ] Checked that any parameters added or modified can be changed from a DAW and have the value updated in the GUI and vice versa
- [ ] Added tooltips to any new labels or buttons to explain them
- [ ] Made sure any new effects or sliders added still work when the range of the slider is changed

**Comment by jameshball** [comment]
Thanks for the PR this is awesome work! Do you mind filling out the template above for testing so I have an idea of what has been tested? Not everything is relevant to this PR so just remove it if you think it's not relevant.

Once you've filled out the template I'll try and do a proper review :)

**Comment by DJLevel3** [comment]
Platforms and software tested
Windows Ableton and Standalone

Testing performed
Approximately 4 hours of use on various Blender projects and methods of making music, zero crashes or issues.

Testing checklist

- [x]  Tested PR on the standalone app
- [x]  Tested PR when using as an audio plugin, e.g. VST or AU
- [x]  Added unit tests to osci-render-test.jucer project when relevant
- [x]  Checked that any parameters added or modified can be changed from a DAW and have the value updated in the GUI and vice versa
- [x]  Added tooltips to any new labels or buttons to explain them
- [x]  Made sure any new effects or sliders added still work when the range of the slider is changed

**Comment by DJLevel3** [comment]
0 blocks doesn't appear to be easily possible without significant rewrite of the audio processing code, so I'll leave it like this for now. Beginning testing.

**Comment by DJLevel3** [comment]
...or I may have forgotten to enable plugin copy so I wasn't actually testing the changes 🤦

**Comment by DJLevel3** [comment]
### Platforms and software tested
Windows - VST3 in Ableton, Standalone

### Testing performed
I have tested a very large GPLA file at high framerate along with the default OBJ file, and everything works as before except the frames now update when stale so there's not a large delay before the frame updates when starting a new MIDI note after some time not playing the previous one.

Testing checklist

- [X]  Tested PR on the standalone app
- [X]  Tested PR when using as an audio plugin, e.g. VST or AU
- [X]  Added unit tests to osci-render-test.jucer project when relevant
- [X]  Checked that any parameters added or modified can be changed from a DAW and have the value updated in the GUI and vice versa
- [X]  Added tooltips to any new labels or buttons to explain them
- [X]  Made sure any new effects or sliders added still work when the range of the slider is changed

**Comment by DJLevel3** [comment]
Strange sounds are happening, I think I know what's wrong though

**Comment by DJLevel3** [comment]
Switched to a new PR, but code is largely the same. Regardless, I'm closing this PR now.

**Pull request closed without merging**
