### PR TITLE
Add 24-bit recording toggle (no GUI yet)

### PR DESCRIPTION
**Pull request by DJLevel3**
In this pull request, I've added a toggle function to output the audio in 24 bits per sample rather than 16. It defaults to on at the moment, but that can easily be changed in ShapeAudioPlayer.java by changing recordHQ to false. The variable can be toggled by calling the function toggleHQRecording() in ShapeAudioPlayer.java, which returns the new state of recordHQ.

### CODE REVIEW

**Comment by jameshball** [comment]
Thanks very much for making a PR!

I am going to add support for some other bit depths to the toggle function so that on the GUI we can have a drop-down that lets you select whatever bit depth you want to record with so that if anyone else wants to record with a specific bit depth they can :)

Reminder to myself that the drop-down or toggle should be disabled whilst recording otherwise things will break!

**Review by jameshball — APPROVED** [review]

**Comment by DJLevel3** [comment]
The selection toggle doesn't get re-enabled when timed recording ends, should probably fix that ;)

**Comment by jameshball** [comment]
Good spot!! I've fixed that and will merge it now :) Please follow up if there are any more issues! Thanks

**Comment by jameshball** [comment]
Closes #83

**Comment by jameshball** [comment]
Changes now live :) https://github.com/jameshball/osci-render/releases

**Pull request merged**
