### PR TITLE
Add Playback Controls for Multiple Files

### PR DESCRIPTION
**Pull request by DJLevel3**
This pull request adds code for playback when a folder is selected, which play the files one by one at a selected framerate. When in playback mode, the hint about changing files changes to a hint about playback controls. Code is properly commented and has protections against common bugs such as setting invalid framerate values.

Changes:

```
Modified files:
- Gui.java (add hotkeys)
- Controller.java (add code for playback and UI modifications)
- osci-render.fxml (add info on playback controls to UI)

New hotkeys:
- i -> play opened files one by one
- u -> decrease playback rate, down to 1 frame per second
- o -> increase playback rate, up to 120 frames per second
```

### CODE REVIEW

**Comment by jameshball** [comment]
Thanks so much for opening this! The majority of the code looks great, just a few minor things that I will look at and test and then I'll merge :)

**Comment by DJLevel3** [comment]
You're welcome! I really liked looking through your code, it was much more organized and well-written than most of my projects. Feel free to make any changes you want to make, more testing could mean more bugs found and fixed!

**Review by DJLevel3 — COMMENTED** [review]
This is definitely improved over my code. As far as I can tell, all looks right!

**Comment by jameshball** [comment]
Thanks! I think my code still has a lot left to be desired, especially `Controller.java` which is getting far too large now... I'm glad it was easy for you to pick up though!

I've had a look over all your code and just made a few small changes:

- Replaced the additional label with different text in the `jkLabel`
  - This also contains the instructions to press i to stop/play
- Fixed bugs where `framesPlaying` would continue to be `true` when opening a single file, whilst a folder's files are playing

image

If there is anything that would have made you understand the codebase quicker, do let me know :)

**Review by jameshball — APPROVED** [review]

**Comment by DJLevel3** [comment]
The one thing that might have helped would have been separate files for different sections of the UI, which would make the code easier to look through for people who aren't already familiar with the files. Aside from that, I liked the way the code was set up quite a bit.

**Pull request merged**
